[build]
  publish = "."
  functions = "netlify/functions"

# endpoints amigáveis -> functions
[[redirects]]
  from = "/api/sheets"
  to = "/.netlify/functions/sheets"
  status = 200
[[redirects]]
  from = "/api/meta-creatives"
  to = "/.netlify/functions/meta"
  status = 200
[[redirects]]
  from = "/api/expad-sales"
  to = "/.netlify/functions/expad"
  status = 200
[[redirects]]
  from = "/api/expad-debug"
  to = "/.netlify/functions/expad-debug"
  status = 200
